### PR TITLE
Issue 3166. Retain focus after autoxubmit.

### LINKED ISSUE #3166: [UX] Views: exposed filter with autosubmit and AJAX loses keyboard focus
## Describe your issue or idea

Views 7.x known issue: https://www.drupal.org/project/views/issues/1217948

https://drupal.stackexchange.com/questions/29503/views-exposed-filter-auto-submit-loses-focus

### Steps to reproduce

1. On a vanilla Backdrop installation, install the Devel module, and enable it + the Devel Generate submodule.
2. Use Devel Generate, to generate a large(ish) amount of content (say 100 or 500 nodes).
3. Edit the "Administer content" view:
   - Enable AJAX from the "Other" section of options.
   - In the "Exposed form" section, click the "Settings" link of the "Exposed form style" option, scroll to the bottom of the dialog, and enable the "Autosubmit" option.
4. Save the view.
5. Head to `admin/content`, and start typing in the "Title contains" exposed filter...

### Actual behavior

When the form autosubmits (after you have typed a couple of characters in the exposed text field), the text box loses focus. The user now needs to click on the text filter again, then as they start typing and autosubmit kicks in, the filter loses focus again. Repeat...

Typing quickly into the exposed filter works fine, however typing slowly will cause focus loss.

Some people report that separating the exposed form into a block fixes the problem, however this is not an option if the view itself is a block display.

### Expected behavior

The exposed text filters do not lose focus as the user types and the results listing gets refreshed.

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes https://github.com/backdrop/backdrop-issues/issues/3166

### CODE REVIEW

File: core/misc/autosubmit.js [hunk 1]
```diff
@@ -37,12 +37,39 @@
...
       var $this = $(this);
+      var $triggering_element = $(element);
+
+      // Variable "element" will have a value only when text fields trigger
+      // this. If element is undefined, then remove the data to prevent
+      // potential focus on a previously processed element.
+      if (element === undefined)  {
+        $('body').removeData('needs-focus');
+      }
+      else if ($triggering_element.parents('.view').length) {
```
Comment (quicksketch) [inline core/misc/autosubmit.js]: I don't think we want to put a Views-specific selector in here. I don't think there would be harm in just always populating this data attribute and always re-focusing the last autocomplete element after autosubmit.

File: core/misc/autosubmit.js [hunk 2]
```diff
@@ -37,12 +37,39 @@
...
+        $('body').data('needs-focus', $triggering_element.attr('id'));
+      }
+
+      // Submit the form.
       $this.find('.autosubmit-click').trigger('click');
     }
 
-    // the change event bubbles so we only need to bind it to the outer form
+    // Listener to ajaxStop will re-focus on the text field as needed.
+    $(document).off('ajaxStop').on('ajaxStop', function () {
```
Comment (quicksketch) [inline core/misc/autosubmit.js]: This `.off('ajaxStop')` would unbind _any_ `ajaxStop` handler. This should be namespaced with `autosubmit` to only remove/add the handler from this file.

File: core/misc/autosubmit.js [hunk 3]
```diff
@@ -37,12 +37,39 @@
...
-    function triggerSubmit (e) {
+    function triggerSubmit (element) {
       var $this = $(this);
+      var $triggering_element = $(element);
+
+      // Variable "element" will have a value only when text fields trigger
+      // this. If element is undefined, then remove the data to prevent
+      // potential focus on a previously processed element.
+      if (element === undefined)  {
+        $('body').removeData('needs-focus');
```
Comment (quicksketch) [inline core/misc/autosubmit.js]: We should probably namespace this data attribute to more clearly identify that it's coming from `autosubmit.js`. I'd suggest `autosubmit-last-focus-id` to be more descriptive.

**Review by quicksketch — COMMENTED** [review]
I tested this and it works well! I worry that this may cause issues in non-Views scenarios (I'm not sure if there are any in core right now to test though). I filed a PR with my suggestions here: https://github.com/argiepiano/backdrop/pull/2

**Comment by quicksketch** [comment]
Merged into 1.x and 1.27.x. Thanks @argiepiano!
