### PR TITLE
Issue #5273: Adjust contextual link triggers to prevent overlaps.

### LINKED ISSUE #5273: Nested contextual links triggers sometimes unreachable
**Description of the bug**

When contextual links regions are nested, the current behavior of Contextual module is to shift the child links down so that the triggers don't overlap each other. However, if the child region is short (e.g., the breadcrumb), then the trigger gets shifted out of the contextual links region and becomes unreachable.

Also, if the right side of the child isn't lined up with the right side of the parent, the child trigger is pushed down unnecessarily.

**Steps To Reproduce**

To reproduce the behavior:

Create a node with "Raw HTML" format and paste in the HTML from the attached file. This creates several sets of nested contextual links that demonstrate the problem. The text in each div describes what the appropriate child trigger action should be.

**Actual behavior**

Child triggers for the short (20px) divs are unreachable. When the child has a right margin, its trigger is pushed down unnecessarily.

**Expected behavior**

Expected trigger position for each example is given by the text of the example.

**Additional information**

- Backdrop CMS version: 1.20.
- Mentioned in https://github.com/backdrop/backdrop-issues/issues/2626#issuecomment-931743014

[contextual_links_demo.html.txt](https://github.com/backdrop/backdrop-issues/files/7268649/contextual_links_demo.html.txt)

### PR DESCRIPTION
**Pull request by bugfolder**
Fixes https://github.com/backdrop/backdrop-issues/issues/5273.

### CODE REVIEW

**Comment by bugfolder** [comment]
I added the test text to node/1 in the Tugboat preview.

File: core/modules/contextual/js/contextual.js [hunk 1]
```diff
@@ -16,30 +16,107 @@ Backdrop.behaviors.contextualLinks = {
...
+      var $trigger = $('<a class="contextual-links-trigger" href="#" />').text(Backdrop.t('Configure')).click(
         function () {
           $links.stop(true, true).slideToggle(100);
           $wrapper.toggleClass('contextual-links-active');
           return false;
         }
       );
       // Attach hover behavior to trigger and ul.contextual-links.
-      $trigger.add($links).on('hover',
+      $trigger.add($links).hover(
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: The hover problem is being addressed separately in https://github.com/backdrop/backdrop-issues/issues/6223. We'll need to revert these after that PR is merged.

File: core/modules/contextual/js/contextual.js [hunk 2]
```diff
@@ -16,30 +16,107 @@ Backdrop.behaviors.contextualLinks = {
...
+     */
+    function adjustContextualLinks() {
+      // Get all wrappers anywhere on the page and some info about each.
+      var allWrappers = [];
+      $('.contextual-links-wrapper', context).each(function() {
+        allWrappers.push({
+          'wrapper': $(this),
+          'regionOffsetBottom': $(this).parent().offset().top + $(this).parent().height(),
+          'hshift': 0,
+          'vshift': 0
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: To avoid these spelling notices, maybe change these variables to `xShift` and `yShift` or `hShift` and `vShift`

File: core/modules/contextual/js/contextual.js [hunk 3]
```diff
@@ -16,30 +16,107 @@ Backdrop.behaviors.contextualLinks = {
...
+                follower.wrapper.css('margin-top', follower.vshift);
+                follower.wrapper.css('margin-left', follower.hshift);
+              }
+            }
+          }
+        }
+      }
+    }
+    $(document).ready(adjustContextualLinks);
+    $(window).on('resize', adjustContextualLinks);
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: We have a method for preventing the resize handler from firing repeatably on resize:

```suggestion
    Backdrop.optimizedResize.add(adjustContextualLinks, 'adjustContextualLinks');
```

File: core/modules/contextual/js/contextual.js (hunk 2 above)
Comment (bugfolder) [reply core/modules/contextual/js/contextual.js]: Will do.

File: core/modules/contextual/js/contextual.js (hunk 1 above)
Comment (bugfolder) [reply core/modules/contextual/js/contextual.js]: Yes, I saw the changes and will do the rebase against 1.x after it's merged.

Comment (bugfolder) [reply core/modules/contextual/js/contextual.js]: New code incorporated.

File: core/modules/contextual/js/contextual.js [hunk 4]
```diff
@@ -23,23 +23,110 @@ Backdrop.behaviors.contextualLinks = {
...
+
+    /**
+     * Adjusts trigger positions in contextual links to avoid overlaps.
+     */
+    function adjustContextualLinks() {
+      // Get all wrappers anywhere on the page and some info about each.
+      var allWrappers = [];
+      $('.contextual-links-wrapper', context).each(function() {
+        allWrappers.push({
+          'wrapper': $(this),
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: It might be good for clarity to prefix this property with a `$`, as is convention for variables that represent jQuery objects.

```suggestion
          '$wrapper': $(this),
```

File: core/modules/contextual/js/contextual.js [hunk 5]
```diff
@@ -23,23 +23,110 @@ Backdrop.behaviors.contextualLinks = {
...
+          'regionOffsetBottom': $(this).parent().offset().top + $(this).parent().height(),
+          'hShift': 0,
+          'vShift': 0
+        });
+      });
+
+      // Reset margins on all wrappers.
+      allWrappers.forEach(function(info) {
+        info.wrapper.css('margin', '0');
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: Then use this everywhere below where `.wrapper` was referenced:

```suggestion
        info.$wrapper.css('margin', '0');
```

File: core/modules/contextual/js/contextual.js [hunk 6]
```diff
@@ -23,23 +23,110 @@ Backdrop.behaviors.contextualLinks = {
...
+                follower.wrapper.css('margin-top', follower.vShift);
+                follower.wrapper.css('margin-left', follower.hShift);
+              }
+            }
+          }
+        }
+      }
+    }
+    $(document).ready(adjustContextualLinks);
+    Backdrop.optimizedResize.add(adjustContextualLinks, 'adjustContextualLinks');
```
Comment (quicksketch) [inline core/modules/contextual/js/contextual.js]: In testing, I found that optimizedResize() fires a lot more often than I would have thought. It also fires on scroll, which we don't want for something like this. So instead a debounce with some documentation might be the best course:
 
```suggestion

    // Usually Backdrop.optimizedResize() would be used for a window resize
    // event, but this potentially expensive operation should be limited to
    // firing infrequently, so Backdrop.debounce() is used here instead.
    $(window).on('resize', Backdrop.debounce(adjustContextualLinks, 500));
```

File: core/modules/contextual/js/contextual.js (hunk 4 above)
Comment (bugfolder) [reply core/modules/contextual/js/contextual.js]: Done.

File: core/modules/contextual/js/contextual.js (hunk 5 above)
Comment (bugfolder) [reply core/modules/contextual/js/contextual.js]: Done.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.26.x. Thanks @bugfolder!
