### PR TITLE
Issue #5835: Resize dialogs after jQuery UI CSS has been loaded.

### LINKED ISSUE #5835: Fixed: Existing Image library popup does not show all images.
## Description of the bug

When there are amount of images in the existing image library and I try to open the image library popup. It shows only part of the row of the images. But when I scroll down the pop-up resizes and shows all the images and the entire image library popup modal.

## Steps To Reproduce

To reproduce the behavior:
1. Add content "Post". 
2. Create “title” and then “Select existing file” for an image field.
3. Image library only shows part of one row.
4. When scrolling down or top it shows the entire image library Pop-up.

The existing Image library should have a number of images to reproduce this.

## Actual behavior
This is how it looks when the pop-up opens first.
edit1

## Expected behavior

The existing image library should show the full window
edit2

## Additional information

- Backdrop CMS version: 1.23.0
- Web server and its version: Nginx/1.18.0
- Operating System and its version: Ubuntu 20.04 lts
- Browser(s) and their versions: Google Chrome V106.0

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/5835

Replaces https://github.com/backdrop/backdrop/pull/4247

### CODE REVIEW

File: core/misc/dialog.js [hunk 1]
```diff
@@ -75,7 +75,20 @@ Backdrop.dialog = function (element, options) {
         })
         .dialog('widget').css('position', 'fixed');
       Backdrop.optimizedResize.add(resetPosition, 'dialogResize.' + dialogId);
-      resetPosition();
+
+      // Because of Chromium's behavior, we must wait until the ajax-loaded
+      // jquery.ui.dialog.css is applied.
+      var waitForCss = function() {
+        var cssOverflowProperty = getComputedStyle($element[0]).getPropertyValue('overflow');
```
Comment (argiepiano) [inline core/misc/dialog.js]: In my original PR I had this variable assignment outside the closure. Scope-wise, your approach may be better, as it keeps the variable within the scope of the closure.  I approached this differently because one of the features of `getComputedStyle()` is that it creates a live object "which updates automatically when the element's styles are changed" according to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle). So, this way, we avoid making a new assignment every time the function is invoked. 

Both approaches work, and I guess it's just a matter of preference.

Comment (quicksketch) [reply core/misc/dialog.js]: Good idea. I didn't know that about `getComputedStyle()`. I moved it to a separate variable again. :+1:

**Comment by quicksketch** [comment]
Merged into 1.x and 1.23.x. Thanks @argiepiano!
