### PR TITLE
Issue #5236: Print test errors inline with other results. 

### LINKED ISSUE #5236: GHA tests: Fix failure output
This is the output I got in one of my recent PRs:

```
Detailed test results
---------------------
Fail      Other      user.test         2163 UserRoleAdminTestCase->testRoleAdmi

Fail      Other      user.test         2174 UserRoleAdminTestCase->testRoleAdmi

Fail      Browser    user.test         2180 UserRoleAdminTestCase->testRoleAdmi
---- User: User role administration (UserRoleAdminTestCase) ----
Fail      Other      user.test         2182 UserRoleAdminTestCase->testRoleAdmi

Fail      Other      user.test         2183 UserRoleAdminTestCase->testRoleAdmi

Fail      Other      user.test         2185 UserRoleAdminTestCase->testRoleAdmi
Status    Group      Filename          Line Function                            
Fail      Browser    user.test         2186 UserRoleAdminTestCase->testRoleAdmi
--------------------------------------------------------------------------------
Fail      Other      user.test         2187 UserRoleAdminTestCase->testRoleAdmi
    The title on the form is "Add role".
Fail      Other      user.test         2215 UserRoleAdminTestCase->testRoleAdmi
    Redirected to correct URL after clicking the "Save role" button.
Fail      Other      user.test         2216 UserRoleAdminTestCase->testRoleAdmi
    Link Configure role does not exist on
    http://localhost/admin/config/people/permissions
    Redirected to correct URL after clicking the "Configure role" operation.
    The title on the form is "Configure role".
    "Save role" button found on "Configure role" form.
    Link Cancel does not exist on
    http://localhost/admin/config/people/permissions
    Redirected to the main roles listing page.
    The role has had its label changed.
    The role has the new label.
```

I'd expect this instead:
```
Detailed test results
---------------------
---- User: User role administration (UserRoleAdminTestCase) ----
Status    Group      Filename          Line Function                  Message
Fail      Other      user.test         2163 testRoleAdministration    The title on the form is "Add role".
Fail      Other      user.test         2174 testRoleAdministration    Redirected to correct URL after clicking the "Save role" button.
Fail      Browser    user.test         2180 testRoleAdministration    Link Configure role does not exist on http://localhost/admin/config/people/permissions
Fail      Other      user.test         2182 testRoleAdministration    Redirected to correct URL after clicking the "Configure role" operation.
Fail      Other      user.test         2183 testRoleAdministration    The title on the form is "Configure role".
Fail      Other      user.test         2185 testRoleAdministration    "Save role" button found on "Configure role" form.
Fail      Browser    user.test         2186 testRoleAdministration    Link Cancel does not exist on http://localhost/admin/config/people/permissions
Fail      Other      user.test         2187 testRoleAdministration    Redirected to the main roles listing page.
Fail      Other      user.test         2215 testRoleAdministration    The role has had its label changed.
Fail      Other      user.test         2216 testRoleAdministration    The role has the new label.
```

...or alternatively this:
```
Detailed test results
---------------------
---- User: User role administration (UserRoleAdminTestCase) ----
Status    Group      Filename          Line Function                            
Fail      Other      user.test         2163 testRoleAdministration
  The title on the form is "Add role".
Fail      Other      user.test         2174 testRoleAdministration
  Redirected to correct URL after clicking the "Save role" button.
Fail      Browser    user.test         2180 testRoleAdministration
  Link Configure role does not exist on http://localhost/admin/config/people/permissions
Fail      Other      user.test         2182 testRoleAdministration
  Redirected to correct URL after clicking the "Configure role" operation.
Fail      Other      user.test         2183 testRoleAdministration
  The title on the form is "Configure role".
Fail      Other      user.test         2185 testRoleAdministration
  "Save role" button found on "Configure role" form.
Fail      Browser    user.test         2186 testRoleAdministration
  Link Cancel does not exist on http://localhost/admin/config/people/permissions
Fail      Other      user.test         2187 testRoleAdministration
  Redirected to the main roles listing page.
Fail      Other      user.test         2215 testRoleAdministration
  The role has had its label changed.
Fail      Other      user.test         2216 testRoleAdministration
  The role has the new label.
```

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/5236

* Wraps lines at 120 characters instead of 80 characters
* Pipes stderr to stdout so that errors are displayed inline instead of after the results
* Fixes to docblock formatting in run-tests.sh

### CODE REVIEW

File: core/scripts/run-tests.sh [hunk 1]
```diff
@@ -782,14 +786,14 @@ function simpletest_script_write_summary($summary_file) {
         $test_class = $result->test_class;
       }
 
-      if($count < 10 ){
+      if ($count < 10 ) {
```
Comment (klonos) [inline core/scripts/run-tests.sh]:
```suggestion
      if ($count < 10) {
```

File: core/scripts/run-tests.sh [hunk 2]
```diff
@@ -782,14 +786,14 @@ function simpletest_script_write_summary($summary_file) {
...
         $summary .= " - `" . $result->status . "` " . trim(strip_tags($result->message)) . ' **' . basename($result->file) . '**:' . $result->line . "\n";
       }
       $count++;
     }
   }
 
-  if($count > 10 ){
+  if ($count > 10){
```
Comment (klonos) [inline core/scripts/run-tests.sh]:
```suggestion
  if ($count > 10) {
```

**Review by klonos — APPROVED** [review]
LGTM 👍🏼
