### PR TITLE
Issue #6777: PHP 8.4 support.

### LINKED ISSUE #6777: PHP 8.4 Support
## Description of the bug

[PHP 8.4 was released last month](https://thephp.foundation/blog/2024/11/21/php-core-roundup-20-php84/) and continues to tighten the screws on less-than-perfect PHP code. Immediately upon switching to PHP 8.4, the homepage of Backdrop has the following errors:

```
Deprecated: Constant E_STRICT is deprecated in /var/www/html/core/includes/bootstrap.inc on line 742

Deprecated: Constant E_STRICT is deprecated in /var/www/html/core/includes/errors.inc on line 28

Deprecated: backdrop_get_query_parameters(): Implicitly marking parameter $query as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/common.inc on line 497

Deprecated: _format_date_callback(): Implicitly marking parameter $matches as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/common.inc on line 2541

Deprecated: actions_execute(): Implicitly marking parameter $entity as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/actions.inc on line 85

Deprecated: comment_access(): Implicitly marking parameter $comment as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/comment/comment.module on line 1513

Deprecated: entity_access(): Implicitly marking parameter $entity as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.module on line 191

Deprecated: entity_access(): Implicitly marking parameter $account as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.module on line 191

Deprecated: entity_build_content(): Implicitly marking parameter $entity as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.module on line 225

Deprecated: taxonomy_vocabulary_static_reset(): Implicitly marking parameter $ids as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/taxonomy/taxonomy.module on line 853

Deprecated: user_has_role(): Implicitly marking parameter $account as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/user/user.module on line 576

Deprecated: UpdateQuery::expression(): Implicitly marking parameter $arguments as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/query.inc on line 1157

Deprecated: MergeQuery::expression(): Implicitly marking parameter $arguments as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/query.inc on line 1420

Deprecated: SelectQueryInterface::getArguments(): Implicitly marking parameter $queryPlaceholder as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 177

Deprecated: SelectQueryInterface::preExecute(): Implicitly marking parameter $query as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 505

Deprecated: SelectQueryExtender::getArguments(): Implicitly marking parameter $queryPlaceholder as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 812

Deprecated: SelectQueryExtender::preExecute(): Implicitly marking parameter $query as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 826

Deprecated: SelectQuery::getArguments(): Implicitly marking parameter $queryPlaceholder as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 1549

Deprecated: SelectQuery::preExecute(): Implicitly marking parameter $query as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/includes/database/select.inc on line 1567

Deprecated: EntityControllerInterface::resetCache(): Implicitly marking parameter $ids as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.controller.inc on line 27

Deprecated: EntityControllerInterface::resetStaticCache(): Implicitly marking parameter $ids as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.controller.inc on line 36

Deprecated: DefaultEntityController::resetCache(): Implicitly marking parameter $ids as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.controller.inc on line 217

Deprecated: DefaultEntityController::resetStaticCache(): Implicitly marking parameter $ids as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/entity/entity.controller.inc on line 235

Deprecated: system_menu_tree_prune_tree(): Implicitly marking parameter $parent_item as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/core/modules/system/system.menu.inc on line 370
```

There are probably many other situations where this occurs. To fix this, our goal should be to bump the test runners from PHP 8.3 to 8.4 and have 100% tests passing.

## Steps To Reproduce

To reproduce the behavior:

1. Install Backdrop normally on PHP 8.3 within DDEV.
2. Edit the `.ddev/config.yml` file and change the php line to `php: 8.4`
3. Restart DDEV to take effect `ddev restart`
4. Visit the homepage, i.e. `https://backdrop.ddev.site`

## Additional information

Corresponding Drupal 10/11 issue is here: https://www.drupal.org/project/drupal/issues/3427903
Corresponding Drupal 7 issue: ?? There may not be one

Add any other information that could help, such as:

- Backdrop CMS version: 1.x (1.30.x)
- Web server and its version: Apache 2.4.62
- PHP version: 8.4.1
- Database sever (MySQL or MariaDB?) and its version: 10.11.10
- Operating System and its version: Ubuntu 24.04
- Browser(s) and their versions: all

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/6777

### CODE REVIEW

File: core/modules/simpletest/backdrop_web_test_case.php [hunk 1]
```diff
@@ -520,10 +520,10 @@ protected function fail($message = NULL, $group = 'Other') {
    *   The type of assertion - examples are "Browser", "PHP".
    * @param $caller
    *   The caller of the error.
-   * @return
-   *   FALSE.
+   * @return false
```
Comment (klonos) [inline core/modules/simpletest/backdrop_web_test_case.php:523]: Shouldn't this remain uppercase?

Comment (quicksketch) [reply core/modules/simpletest/backdrop_web_test_case.php:523]: We're not consistent on it. Up until recently I was using `FALSE` and `NULL` in phpDoc but @indigoxela pointed out lowercase is more common.

Comment (quicksketch) [reply core/modules/simpletest/backdrop_web_test_case.php:523]: This inconsistency was discovered as part of https://github.com/backdrop/backdrop/pull/4915.

Comment (herbdool) [reply core/modules/simpletest/backdrop_web_test_case.php:523]: I think we decided to standardize on lowercase.

File: core/includes/actions.inc [hunk 2]
```diff
@@ -73,16 +73,16 @@ function actions_get_info($action_name = NULL) {
  *
  * @param string $action_name
  *   The machine name of the action to be executed.
- * @param Entity $entity
+ * @param ?Entity|null $entity
```
Comment (indigoxela) [inline core/includes/actions.inc]: Did the IDE suggest this doc block notation?

Because PHPStan chokes on that. It accepts's either `@param Entity|null $entity` or `@param ?Entity $entity`, but not the combination of question mark and types separated by `|`.

Didn't find any official recommendation for nullable types in doc blocks, though.

Comment (quicksketch) [reply core/includes/actions.inc]: It was not suggested, I added it in some places because we has this `|null` notation in other places. I would be okay removing it from all places where the parameter is already indicated as nullable due to the question mark.

File: core/includes/actions.inc [hunk 3]
```diff
@@ -73,16 +73,16 @@ function actions_get_info($action_name = NULL) {
...
  *   comment object.
  *
- * @return
+ * @return mixed
  *   The result of the executed action callback.
  *
  * @ingroup actions
  */
-function actions_execute($action_name, Entity $entity = NULL, &$context) {
+function actions_execute($action_name, ?Entity $entity = NULL, &$context) {
```
Comment (indigoxela) [inline core/includes/actions.inc]: Optional parameter $entity declared before required parameter $context (on php 8.3).
That nagging seems to be new.

Comment (quicksketch) [reply core/includes/actions.inc]: Hm, sure enough. Well that means if $context is required, Entity doesn't need to be optional (but it still needs to be nullable). So this:

```suggestion
function actions_execute($action_name, ?Entity $entity, &$context) {
```

File: core/includes/actions.inc (hunk 2 above)
Comment (quicksketch) [reply core/includes/actions.inc]:
```suggestion
 * @param ?Entity $entity
```

Comment (indigoxela) [reply core/includes/actions.inc]: Personally, I find it more readable if the types are fully written, like `@param Entity|null $entity`.
A single character's easily overlooked.
Adding `null` if it's nullable seems like a good idea. I belief, we have several misleading doc blocks in core re that.

But maybe that's just me - and I'm no doc block expert. :wink: Hopefully someone finds a good hint somewhere.

File: core/includes/errors.inc [hunk 4]
```diff
@@ -25,7 +25,6 @@ function backdrop_error_levels() {
     E_USER_ERROR => array('User error', WATCHDOG_ERROR),
     E_USER_WARNING => array('User warning', WATCHDOG_WARNING),
     E_USER_NOTICE => array('User notice', WATCHDOG_NOTICE),
-    E_STRICT => array('Strict warning', WATCHDOG_DEBUG),
```
Comment (indigoxela) [inline core/includes/errors.inc:28]: My suspicion is, that we still need E_STRICT for PHP versions before 8.4.
It's mentioned in every php.ini for every version other than 8.4.
We could just remove it for 8.4, leave it in place for all previous versions.

Otherwise something might slip through...

File: core/includes/actions.inc [hunk 5]
```diff
@@ -73,16 +73,16 @@ function actions_get_info($action_name = NULL) {
...
  *   comment object.
  *
- * @return
+ * @return mixed
  *   The result of the executed action callback.
  *
  * @ingroup actions
  */
-function actions_execute($action_name, Entity $entity = NULL, &$context) {
+function actions_execute($action_name, ?Entity $entity, &$context) {
```
Comment (herbdool) [inline core/includes/actions.inc:85]: I'm guessing this still needs `= NULL` for BC.

File: core/includes/common.inc [hunk 6]
```diff
@@ -483,18 +483,18 @@ function backdrop_get_feeds($delimiter = "\n") {
 /**
  * Processes a URL query parameter array to remove unwanted elements.
  *
- * @param $query
+ * @param ?array|null $query
```
Comment (indigoxela) [inline core/includes/common.inc]: In order to make it easier to work with PHPStan, not harder, we should use a comment syntax it recognizes (and doesn't flag as error).

I'd suggest to stick with `@param array|null` (no question mark for nullable types in doc block).

I didn't find any official recommendation for notation of nullable types in doc blocks, though.

File: core/includes/actions.inc (hunk 5 above)
Comment (quicksketch) [reply core/includes/actions.inc:85]: PHP 8.4 requires that optional parameters follow required ones. In this case `&$context` is a required parameter, so all calling functions need to pass in `NULL` or an `$entity` value already, because they also need to pass in `$context`, otherwise you'd get a missing argument PHP error. So this is a safe change to make.

File: core/includes/common.inc (hunk 6 above)
Comment (quicksketch) [reply core/includes/common.inc]: You're right, I thought PHPStorm (which I believe uses PHPStan) only worked with `?array` syntax, but it looks like `array|null` is also totally acceptable. Doing `?array|null` is redundant, though in PHPStorm it does not throw any linting errors if both are used. If `array|null` throws no errors anywhere, let's stick with that as you suggest.

File: core/includes/errors.inc (hunk 4 above)
Comment (quicksketch) [reply core/includes/errors.inc:28]: Thanks, I added a version check and restored E_STRICT to the list by appending it to the end of the array if on versions older than 8.4.

File: core/includes/common.inc (hunk 6 above)
Comment (quicksketch) [reply core/includes/common.inc]: PR is updated to use `@param array|null` syntax everywhere, which makes for fewer overall changes and is in my opinion, easier to understand.

File: core/modules/layout/layout.admin.inc [hunk 7]
```diff
@@ -2014,7 +2014,7 @@ function layout_block_disable_page(Layout $layout, Block $block, $renderer_name)
  *
  * @ingroup forms
  */
-function layout_condition_add_form($form, &$form_state, Layout $layout = NULL, Block $block = NULL, LayoutMenuItem $menu_item = NULL, $condition_id = NULL) {
+function layout_condition_add_form($form, &$form_state, ?Layout $layout = NULL, ?Block $block = NULL, ?LayoutMenuItem $menu_item = NULL, $condition_id = NULL) {
```
Comment (indigoxela) [inline core/modules/layout/layout.admin.inc:2018]: I wonder if Layout could ever be null. Probably not a topic here in this issue, as this "null" pre-existed, but still a bit odd. The same seems true for layout_condition_edit_title().

File: core/modules/layout/layout.context.admin.inc [hunk 8]
```diff
@@ -133,15 +133,15 @@ function layout_context_add_form($form, &$form_state, Layout $layout = NULL, $co
...
+ * @param ?Layout $layout
  *   The layout to which a context is being added.
  * @param int|null $relationship_id
  *   The ID of the relationship being configured. If adding a new
  *   relationship, no value will be passed in.
  *
  * @ingroup forms
  */
-function layout_context_relationship_add_form($form, &$form_state, Layout $layout = NULL, $relationship_id = NULL) {
+function layout_context_relationship_add_form($form, &$form_state, ?Layout $layout, $relationship_id = NULL) {
```
Comment (indigoxela) [inline core/modules/layout/layout.context.admin.inc]: Similar to above - could Layout ever be null when adding a relationship?

The "NULL" assignment has been stripped, BTW, and the doc block uses nullable type notation. Is that an oversight, or by intention? (Using nullable type notation like that is OK for doc block, btw, so that's not my concern here.)

File: core/modules/simpletest/backdrop_web_test_case.php [hunk 9]
```diff
@@ -662,7 +662,6 @@ protected abstract function tearDown();
   public function errorHandler($severity, $message, $file = NULL, $line = NULL) {
     if ($severity & error_reporting()) {
       $error_map = array(
-        E_STRICT => 'Run-time notice',
```
Comment (indigoxela) [inline core/modules/simpletest/backdrop_web_test_case.php:665]: Do we also need E_STRICT for PHP version < 8.4 for BackdropTestCase::errorHandler()?

File: core/includes/actions.inc (hunk 3 above)
Comment (indigoxela) [reply core/includes/actions.inc]: You seem to have fixed it "in mind", but forgot to actually fix it in code. At least, you didn't commit/push it.

The nagging persists, as it's still `?Entity $entity = NULL`. (Unfortunately I can't "unresolve" here permission-wise.)

Comment (herbdool) [reply core/includes/actions.inc]: I removed the NULL.

File: core/modules/layout/layout.context.admin.inc (hunk 8 above)
Comment (avpaderno) [reply core/modules/layout/layout.context.admin.inc]: I take that `?Layout $layout = NULL` should be used, since it is backward compatible with `Layout $layout = NULL` for code that calls `layout_context_relationship_add_form()` as `layout_context_relationship_add_form($form, $form_state)`. `layout_context_relationship_add_form($form, &$form_state, Layout ?$layout, $relationship_id = NULL)` requires at least three arguments, since the third one is not optional, even if the function could be called as `layout_context_relationship_add_form($form, $form_state, NULL)`.

Comment (avpaderno) [reply core/modules/layout/layout.context.admin.inc]: I wonder too if it makes sense to pass a `NULL` layout. This should be changed in a different issue, though, as this issue should make the code compatible with PHP 8.4.  
If it makes sense, `layout_context_relationship_add_form()` needs to be changed because it accesses `$layout->relationships` without first verifying `$layout` is not `NULL`.

Comment (quicksketch) [reply core/modules/layout/layout.context.admin.inc]: Thanks, added `= NULL` even though it probably should be required. Separate issue.

File: core/modules/layout/layout.admin.inc (hunk 7 above)
Comment (quicksketch) [reply core/modules/layout/layout.admin.inc:2018]: As with other places, we're leaving the optional and default NULL values in place where possible for now, just to get onto PHP 8.4. We could clean these up in a separate issue.

File: core/modules/simpletest/backdrop_web_test_case.php (hunk 9 above)
Comment (quicksketch) [reply core/modules/simpletest/backdrop_web_test_case.php:665]: Thanks, I restored E_STRICT the same as we did in `backdrop_error_levels()`.

File: core/includes/actions.inc (hunk 2 above)
Comment (quicksketch) [reply core/includes/actions.inc]: The syntax everywhere should now be `* @param Entity|null $entity` in docblocks (no question mark, but `null` specified).

File: core/modules/layout/layout.admin.inc (hunk 7 above)
Comment (quicksketch) [reply core/modules/layout/layout.admin.inc:2018]: I changed my mind here and went ahead and just made `$layout` a non-nullable required parameter, since the contents of the function may fail if `$layout` is not passed in.

File: core/modules/layout/layout.context.admin.inc (hunk 8 above)
Comment (quicksketch) [reply core/modules/layout/layout.context.admin.inc]: I changed my mind here and went ahead and made `$layout` a required and non-nullable parameter here.

File: core/modules/layout/layout.admin.inc (hunk 7 above)
Comment (quicksketch) [reply core/modules/layout/layout.admin.inc:2018]: Well I tried making `$layout` required but turns out there is a valid use-case for a `NULL` layout. This same form is used to add conditions to menu items. In this situation, multiple layouts may share the same menu route, and in that situation, both `$layout` and `$block` are NULL. Only `$menu_item` has a value.

So I put this back to the way it was, with `$layout` both being optional and having a `NULL` default.
