### PR TITLE
Issue #688: Fixed Field default widgets are not actually set as defaults...

### LINKED ISSUE #688: Field default widgets are not actually set as defaults
Modules that provide fields are encouraged to specify a default_widget in hook_field_info() But the field UI does not use this information to set defaults. Instead, the list of widgets for any given field type seems to always be a reverse-alpha-sorted list of widgets, so the one with the name that comes alphabetically last becomes the defacto default.

An example of this bug in action is to apply the PR from https://github.com/backdrop/backdrop-issues/issues/684 and notice that the text (long) field uses the textfield widget by default, instead of the defined textarea widget. 

```
'default_widget' => 'text_textarea',
```

We need to fix the bug that default widgets are not actually default widgets. This means passing the widget information into the javascript that selects the in the Field UI, so that it can determine what the default should be, and select it.

Also, It would also be nice if we could alpha sort the list of widgets.

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/684

I noticed this bug also exists in Drupal 7, and created an issue here: https://www.drupal.org/node/2421833#comment-9595973

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop/backdrop-issues/issues/688

### CODE REVIEW

File: core/modules/field_ui/js/field_ui.js [hunk 1]
```diff
@@ -93,7 +94,10 @@ jQuery.fn.fieldUIPopulateOptions = function (options, selected) {
     jQuery.each(options, function (value, text) {
       // Figure out which value should be selected. The 'selected' param
       // takes precedence.
-      var is_selected = ((typeof selected != 'undefined' && value == selected) || (typeof selected == 'undefined' && text == previousSelectedText));
+      var is_selected = (
+        (typeof selected != 'undefined' && value == selected) ||
+        (typeof selected == 'undefined' && text == previousSelectedText) ||
+        (value == widgetDefault));
```
Comment (quicksketch) [inline core/modules/field_ui/js/field_ui.js]: I think this last condition needs to check that `selected` is undefined. Otherwise if a default value is set and it is different from the widget default, we may end up with two `<option selected="selected">` tags.

So I think the last line should be:

```
(typeof selected == 'undefined' && value == widgetDefault));
```

**Comment by jenlampton** [comment]
Pushed the fix and also updated the commit message.
