### PR TITLE
Issue #4392: Add command line option to skip MyISAM conversion

### LINKED ISSUE #4392: Get run-tests.sh script with profile cache running on newer environments
**Description of the bug**

Currently running tests via script run-tests.sh _with profile cache on_ doesn't work on newer environments, namely mysql 5.7+ or mariadb 10.2.2+.

These db versions with settings like listed below choke on the `alter table` to MyISAM in backdrop_web_test_case_cache.php.

Message:
`ERROR: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
`

**Steps To Reproduce**

Make sure your db is new enough (on Ubuntu Bionic, Debian Buster...) and has following variables set:

- innodb_large_prefix ON
- innodb_default_row_format dynamic
- innodb_file_per_table ON
- innodb_file_format Barracuda

Then download and install Backdrop (via install.sh or however).

Then go to the Backdrop root directory and try to run the tests with profile caching (param --cache):

`./core/scripts/run-tests.sh --url http://localhost/ --force --cache BlockTestCase`

**Actual behavior**

PDO Exception and no tests run at all.

**Expected behavior**

Tests running.

**Additional information**

I ran into this issue when trying to get Simpletests working with travisCI, but now found a way to reproduce.

Here's the [Zulipchat thread](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/pdo.20when.20running.20tests) with my question.

Joseph Flatt provided a trick: setting `$test->prepareCache(TRUE)` in run-tests.sh bypasses the table conversions to MyISAM - and then the tests run without problem. But patching around in core is no real solution, of course.

**Please note:**

Variable innodb_large_prefix is deprecated in both, mysql and mariadb, and large prefixes will be the default setting after this variable has gone.

See details to the large prefix variable for [MySQL](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) and [MariaDB](https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix).

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes https://github.com/backdrop/backdrop-issues/issues/4392

### CODE REVIEW

File: core/scripts/run-tests.sh [hunk 1]
```diff
@@ -191,8 +191,13 @@ if ($args['cache']) {
   simpletest_script_init(NULL);
 
   echo "\nPreparing database and configuration cache for profiles\n";
+  $skip_myisam = $args['skip-myisam'];
+  if ($skip_myisam) {
+    $skip_myisam = TRUE;
```
Comment (docwilmot) [inline core/scripts/run-tests.sh]: Wouldnt `$skip_myisam` always be already true at this statement?

Comment (indigoxela) [reply core/scripts/run-tests.sh]: Sort of. It would be `1`, but I thought, an explicit `TRUE` is cleaner, as the default value if not set is an explicit `FALSE`.

Bad idea?

Comment (docwilmot) [reply core/scripts/run-tests.sh]: I dont know TBH. Cant hurt to make it explicit, as you say.

Comment (indigoxela) [reply core/scripts/run-tests.sh]: Ah, OK... I took a closer look and realized, that the conversion to bool already happens in function simpletest_script_parse_args(), so that's actually redundant. :+1:

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.19.x!
