### PR TITLE
Issue #6439: Preserve whitespace within pre tags on CKEditor 5 save.

### LINKED ISSUE #6439: CKeditor 5 removes whitespace from within `<pre>` tags
## Description of the bug

After switching to CKeditor 5, pages on the documentation site that previously had nicely indented code samples, loose the whitespace after saving with ckeditor5 enabled.

This appears to be a known issue with ckeditor5. There is both an issue and a Pull Request with a potential solution:
* issue: https://github.com/ckeditor/ckeditor5/issues/16124
* PR: https://github.com/ckeditor/ckeditor5/pull/16125

## Steps To Reproduce

To reproduce the behavior:
1. Create a page in "Raw HTML" mode
2. Add some nicely idndened code in a `<pre>` tag, something like
```
<pre>
h3 {
    font-size: 2em;
}
</pre>
```
4. Save.
5. Edit the page, switch to a text format with ckeditor5 enabled.
6. Save. **See how whitespace has been removed from display**
8. Edit the page again. **See how whitespace has also been removed from the database**

## Actual behavior

Whitespace deleted.

## Expected behavior

Whitespace preserved.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.27.1

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop/backdrop-issues/issues/6439

### CODE REVIEW

File: core/modules/ckeditor5/js/ckeditor5.formatter.js [hunk 1]
```diff
@@ -203,6 +209,29 @@
...
+
+    /**
+     * Checks whether a line belongs to a preformatted (`<pre>`) block.
+     *
+     * @param {String} line
+     *   String to check.
+     * @param {String|false} isPreviousLinePreFormatted
+     *   Information on whether the previous line was preformatted (and how).
+     */
+     _isPreformattedBlockLine(line, isPreviousLinePreFormatted) {
```
Comment (indigoxela) [inline core/modules/ckeditor5/js/ckeditor5.formatter.js]: ^^ This one line has odd indent. It's 5 spaces instead of 4.

Comment (quicksketch) [inline core/modules/ckeditor5/js/ckeditor5.formatter.js]: Thanks, good catch!

```suggestion
    _isPreformattedBlockLine(line, isPreviousLinePreFormatted) {
```

I'll apply this later so the sandbox doesn't get rebuilt.

Comment (indigoxela) [reply core/modules/ckeditor5/js/ckeditor5.formatter.js]: > I'll apply this later so the sandbox doesn't get rebuilt.

No problem, I'm testing locally, anyway. :wink:

**Comment by quicksketch** [comment]
Merged this into 1.x and 1.29.x. Thank you @indigoxela and @herbdool for reviewing!
